# Generated by Django 3.2.4 on 2021-06-22 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlantOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('potting_needs', models.CharField(max_length=200)),
                ('temp_needs', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('plant_pic', models.URLField(null=True)),
                ('pest_watch', models.BooleanField(default=False)),
                ('light_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantappapi.light')),
                ('plant_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantappapi.plantowner')),
                ('water_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantappapi.water')),
            ],
        ),
    ]
