# Generated by Django 3.2.4 on 2021-06-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantappapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_pic',
            field=models.ImageField(null=True, upload_to='plants'),
        ),
    ]
