# Generated by Django 3.2.4 on 2021-06-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantappapi', '0002_alter_plant_plant_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_pic',
            field=models.URLField(null=True),
        ),
    ]
