# Generated by Django 3.2.4 on 2021-06-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantappapi', '0003_water'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('potting_needs', models.CharField(max_length=200)),
                ('temp_needs', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('plant_pic', models.ImageField(null=True, upload_to='plantimage')),
                ('light_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantappapi.light')),
                ('plant_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantappapi.plantowner')),
                ('water_needs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantappapi.water')),
            ],
        ),
    ]
